version: '3'

services:
  bc_db:
    image: postgres:alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
  bc_redis:
    image: bitnami/redis:latest
    env_file:
      - .env
    ports:
      - "6379:6379"
  bc_app:
    build: .
    expose:
      - "8080"
    env_file:
      - .env
    links:
      - bc_db
      - bc_redis
    restart: always
  nginx:
    build: containers/services/nginx
    ports:
      - "80:80"
    restart: always
    links:
      - bc_app
