// Code generated by go-swagger; DO NOT EDIT.

package blockchain_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBlockHandlerFunc turns a function with the right signature into a get block handler
type GetBlockHandlerFunc func(GetBlockParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBlockHandlerFunc) Handle(params GetBlockParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetBlockHandler interface for that can handle valid get block params
type GetBlockHandler interface {
	Handle(GetBlockParams, interface{}) middleware.Responder
}

// NewGetBlock creates a new http.Handler for the get block operation
func NewGetBlock(ctx *middleware.Context, handler GetBlockHandler) *GetBlock {
	return &GetBlock{Context: ctx, Handler: handler}
}

/* GetBlock swagger:route GET /block/{net_code}/{hash} blockchain_info getBlock

GetBlock get block API

*/
type GetBlock struct {
	Context *middleware.Context
	Handler GetBlockHandler
}

func (o *GetBlock) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetBlockParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
