// Code generated by go-swagger; DO NOT EDIT.

package blockchain_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/cegorah/blockchain_info/models"
)

// GetTxInfoOKCode is the HTTP code returned for type GetTxInfoOK
const GetTxInfoOKCode int = 200

/*GetTxInfoOK Returns an information about a transaction

swagger:response getTxInfoOK
*/
type GetTxInfoOK struct {

	/*
	  In: Body
	*/
	Payload models.Transactions `json:"body,omitempty"`
}

// NewGetTxInfoOK creates GetTxInfoOK with default headers values
func NewGetTxInfoOK() *GetTxInfoOK {

	return &GetTxInfoOK{}
}

// WithPayload adds the payload to the get tx info o k response
func (o *GetTxInfoOK) WithPayload(payload models.Transactions) *GetTxInfoOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get tx info o k response
func (o *GetTxInfoOK) SetPayload(payload models.Transactions) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTxInfoOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Transactions{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetTxInfoBadRequestCode is the HTTP code returned for type GetTxInfoBadRequest
const GetTxInfoBadRequestCode int = 400

/*GetTxInfoBadRequest Wrong request parameters

swagger:response getTxInfoBadRequest
*/
type GetTxInfoBadRequest struct {
}

// NewGetTxInfoBadRequest creates GetTxInfoBadRequest with default headers values
func NewGetTxInfoBadRequest() *GetTxInfoBadRequest {

	return &GetTxInfoBadRequest{}
}

// WriteResponse to the client
func (o *GetTxInfoBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// GetTxInfoNotFoundCode is the HTTP code returned for type GetTxInfoNotFound
const GetTxInfoNotFoundCode int = 404

/*GetTxInfoNotFound Transaction not found

swagger:response getTxInfoNotFound
*/
type GetTxInfoNotFound struct {
}

// NewGetTxInfoNotFound creates GetTxInfoNotFound with default headers values
func NewGetTxInfoNotFound() *GetTxInfoNotFound {

	return &GetTxInfoNotFound{}
}

// WriteResponse to the client
func (o *GetTxInfoNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// GetTxInfoInternalServerErrorCode is the HTTP code returned for type GetTxInfoInternalServerError
const GetTxInfoInternalServerErrorCode int = 500

/*GetTxInfoInternalServerError Internal server error

swagger:response getTxInfoInternalServerError
*/
type GetTxInfoInternalServerError struct {
}

// NewGetTxInfoInternalServerError creates GetTxInfoInternalServerError with default headers values
func NewGetTxInfoInternalServerError() *GetTxInfoInternalServerError {

	return &GetTxInfoInternalServerError{}
}

// WriteResponse to the client
func (o *GetTxInfoInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
