// Code generated by go-swagger; DO NOT EDIT.

package blockchain_info

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTxInfoHandlerFunc turns a function with the right signature into a get tx info handler
type GetTxInfoHandlerFunc func(GetTxInfoParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTxInfoHandlerFunc) Handle(params GetTxInfoParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetTxInfoHandler interface for that can handle valid get tx info params
type GetTxInfoHandler interface {
	Handle(GetTxInfoParams, interface{}) middleware.Responder
}

// NewGetTxInfo creates a new http.Handler for the get tx info operation
func NewGetTxInfo(ctx *middleware.Context, handler GetTxInfoHandler) *GetTxInfo {
	return &GetTxInfo{Context: ctx, Handler: handler}
}

/* GetTxInfo swagger:route GET /tx/{net_code}/{hash} blockchain_info getTxInfo

GetTxInfo get tx info API

*/
type GetTxInfo struct {
	Context *middleware.Context
	Handler GetTxInfoHandler
}

func (o *GetTxInfo) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTxInfoParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
